"""Generates generated/OGDEvents.cs and generated/OGDEvents.js from the event code tables in events/.

Run from the repo root: python scripts/generate_event_codes.py
"""
# import standard libraries
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

ROOT   : Path = Path(__file__).resolve().parent.parent
EVENTS : Path = ROOT / "events"
OUT    : Path = ROOT / "generated"

# The 5000 and 6000 blocks mirror the 4000 families with a different actor, so their codes come from 4000.
MIRRORS : Dict[int, int] = {5000: 4000, 6000: 4000}
HEADER : List[str] = [
    "Generated by scripts/generate_event_codes.py in ogd-standards from the event standard.",
    "Do not edit by hand. Regenerate it when the standard changes.",
]
SUMMARY : List[str] = [
    "Event codes from the OpenGameData event standard, grouped by category and family.",
    "Game-specific events can use the X900-X999 codes of any block, or the 9000 block.",
]
# The header row of each kind of code table. Codes are only read from the first column of these tables.
CODE_TABLES : Dict[str, List[str]] = {
    "Event Code": ["Event Code", "Event Name", "Description"],
    "Code Range": ["Code Range", "Family", "Family Description"],
}

CATEGORY_HEADING : re.Pattern = re.compile(r"^## (.+?) \((\d{4})[–-](\d{4})\)\s*$")
FAMILY_HEADING   : re.Pattern = re.compile(r"^### (.+?) \((\d{4})[–-](\d{4})\)\s*$")
CODE             : re.Pattern = re.compile(r"\d{4}")
RANGE            : re.Pattern = re.compile(r"(\d{4})\s*[–-]\s*(\d{4})")
SEPARATOR        : re.Pattern = re.compile(r":?-+:?")


def _toPascal(text:str) -> str:
    """Turns a heading or event name from the standard into a PascalCase identifier.

    :param text: The heading or name, e.g. "place object (valid)".
    :type text: str
    :return: The identifier, e.g. "PlaceObjectValid".
    :rtype: str
    """
    return "".join(w[0].upper() + w[1:] for w in re.findall(r"[A-Za-z0-9]+", text))


def _tableCells(line:str) -> Optional[List[str]]:
    """Splits a markdown table row into its cells. The outer pipes are optional, as in pandoc.

    :param line: A line from an event file.
    :type line: str
    :return: The trimmed cells, or None if the line has no pipe.
    :rtype: Optional[List[str]]
    """
    _line : str = line.strip()
    if "|" not in _line:
        return None
    return [cell.strip() for cell in _line.strip("|").split("|")]


def _hasCode(row:List[str]) -> bool:
    """Checks whether any cell of a table row holds a 4-digit code.

    :param row: The cells of a table row.
    :type row: List[str]
    :return: True if the first cell contains a 4-digit number, or another cell is one (ignoring markdown emphasis).
    :rtype: bool
    """
    return bool(CODE.search(row[0])) or any(CODE.fullmatch(cell.strip("*_`")) for cell in row[1:])


def _parseFile(path:Path) -> Tuple[Dict[str, Any], List[Dict[str, Any]], List[Dict[str, Any]]]:
    """Reads the category, its families and their events, and the code ranges from one event file.

    :param path: A category file from events/, e.g. 4000_player-events.md.
    :type path: Path
    :return: The category, its families, and the code ranges listed in its tables.
    :rtype: Tuple[Dict[str, Any], List[Dict[str, Any]], List[Dict[str, Any]]]
    """
    category : Optional[Dict[str, Any]] = None
    family   : Optional[Dict[str, Any]] = None
    families : List[Dict[str, Any]]     = []
    ranges   : List[Dict[str, Any]]     = []
    header   : Optional[str]            = None
    for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        row : Optional[List[str]] = _tableCells(line)
        if row is None:
            header = None
            if m := CATEGORY_HEADING.match(line):
                _words : str = _toPascal(m.group(1))
                category = {'name': _words[:-len("Events")] if _words.endswith("Events") else _words,
                            'start': int(m.group(2)), 'end': int(m.group(3))}
            elif m := FAMILY_HEADING.match(line):
                family = {'name': _toPascal(m.group(1)), 'start': int(m.group(2)), 'end': int(m.group(3)), 'events': []}
                families.append(family)
        elif header is None:
            header = row[0]
            if header in CODE_TABLES:
                _columns : List[str] = CODE_TABLES[header]
                assert row[:3] == _columns, f"{path.name}:{number}: the columns should be {' | '.join(_columns)}"
            else:
                assert not _hasCode(row), f"{path.name}:{number}: code outside a code table"
        elif header not in CODE_TABLES:
            assert not _hasCode(row), f"{path.name}:{number}: code outside a code table"
        elif not SEPARATOR.fullmatch(row[0]):
            _code  : Optional[re.Match] = CODE.fullmatch(row[0])
            _range : Optional[re.Match] = RANGE.fullmatch(row[0])
            assert len(row) >= 3 and (_code or _range), f"{path.name}:{number}: can't read the row {line.strip()!r}"
            if _code:
                assert family, f"{path.name}:{number}: event {row[0]} is not under a family heading"
                family['events'].append({'code': int(row[0]), 'name': _toPascal(row[1]), 'description': row[2]})
            elif _range:
                ranges.append({'start': int(_range.group(1)), 'end': int(_range.group(2)), 'name': _toPascal(row[1])})
    assert category, f"{path.name}: no category heading"
    return category, families, ranges


def _loadCategories() -> List[Dict[str, Any]]:
    """Reads every category file, fills in the 5000 and 6000 families from 4000, and checks the result.

    :return: The categories that have at least one event, in code order.
    :rtype: List[Dict[str, Any]]
    """
    categories : Dict[int, Dict[str, Any]] = {}
    for path in sorted(EVENTS.glob("[0-9]000_*.md")):
        category, families, ranges = _parseFile(path)
        assert category['start'] == int(path.name[:4]), f"{path.name}: the heading should start at {path.name[:4]}"
        category['families'], category['ranges'] = families, ranges
        categories[category['start']] = category

    for start, source in MIRRORS.items():
        category, offset = categories[start], start - source
        for r in category['ranges']:
            if r['name'] in ("Reserved", "Custom"):
                continue
            original = next((f for f in categories[source]['families'] if f['start'] == r['start'] - offset), None)
            assert original and original['name'] == r['name'], f"{start}: {r['name']} doesn't mirror a {source} family"
            category['families'].append({
                'name': r['name'], 'start': r['start'], 'end': r['end'],
                'events': [{'code': e['code'] + offset, 'name': e['name'],
                            'description': f"Mirrors {e['code']}: {e['description']}"} for e in original['events']],
            })

    result : List[Dict[str, Any]] = [c for c in categories.values() if any(f['events'] for f in c['families'])]
    _checkCategories(result)
    return result


def _checkCategories(categories:List[Dict[str, Any]]) -> None:
    """Stops with an error if a family or event is out of range, duplicated, or would make a bad identifier.

    :param categories: The categories to check.
    :type categories: List[Dict[str, Any]]
    """
    seen : Set[int] = set()
    for c in categories:
        assert c['name'] and not c['name'][0].isdigit(), f"bad name for category {c['start']}"
        names : List[str] = [f['name'] for f in c['families']]
        assert len(names) == len(set(names)), f"duplicate family name in {c['name']}"
        for f in c['families']:
            assert c['start'] <= f['start'] <= f['end'] <= c['end'], f"{f['name']} is outside {c['name']}"
            assert f['name'] and not f['name'][0].isdigit(), f"bad name for family {f['start']}"
            assert f['name'] not in (c['name'], "OGDEvents"), f"{f['name']} clashes with its category"
            event_names : List[str] = [e['name'] for e in f['events']]
            assert len(event_names) == len(set(event_names)), f"duplicate event name in {f['name']}"
            for e in f['events']:
                assert f['start'] <= e['code'] <= f['end'], f"{e['code']} is outside {f['name']}"
                assert e['code'] not in seen, f"duplicate code {e['code']}"
                assert e['name'] and not e['name'][0].isdigit() and e['name'] != f['name'], f"bad name for {e['code']}"
                seen.add(e['code'])


def _toCSharp(categories:List[Dict[str, Any]]) -> str:
    """Formats the categories as nested static classes of int constants.

    :param categories: The checked categories.
    :type categories: List[Dict[str, Any]]
    :return: The contents of OGDEvents.cs.
    :rtype: str
    """
    _xml = lambda s: s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    lines : List[str] = [f"// {h}" for h in HEADER] + ["", "namespace OGD {", "", "    /// <summary>"]
    lines += [f"    /// {s}" for s in SUMMARY] + ["    /// </summary>", "    static public class OGDEvents {"]
    for c in categories:
        lines += ["", f"        static public class {c['name']} {{"]
        for f in c['families']:
            lines += ["", f"            static public class {f['name']} {{"]
            for e in f['events']:
                lines += [f"                /// <summary>{_xml(e['description'])}</summary>",
                          f"                public const int {e['name']} = {e['code']};"]
            lines.append("            }")
        lines.append("        }")
    lines += ["    }", "}"]
    return "\n".join(lines) + "\n"


def _toJavaScript(categories:List[Dict[str, Any]]) -> str:
    """Formats the categories as nested frozen objects of numbers.

    :param categories: The checked categories.
    :type categories: List[Dict[str, Any]]
    :return: The contents of OGDEvents.js.
    :rtype: str
    """
    _doc = lambda s: s.replace("*/", "*\\/")
    lines : List[str] = [f"// {h}" for h in HEADER] + ["", "/**"] + [f" * {s}" for s in SUMMARY] + [" */"]
    lines.append("export const OGDEvents = Object.freeze({")
    for c in categories:
        lines.append(f"    {c['name']}: Object.freeze({{")
        for f in c['families']:
            lines.append(f"        {f['name']}: Object.freeze({{")
            for e in f['events']:
                lines += [f"            /** {_doc(e['description'])} */", f"            {e['name']}: {e['code']},"]
            lines.append("        }),")
        lines.append("    }),")
    lines.append("});")
    return "\n".join(lines) + "\n"


def Main() -> None:
    """Regenerates both files in generated/."""
    categories : List[Dict[str, Any]] = _loadCategories()
    OUT.mkdir(exist_ok=True)
    (OUT / "OGDEvents.cs").write_text(_toCSharp(categories), encoding="utf-8", newline="\n")
    (OUT / "OGDEvents.js").write_text(_toJavaScript(categories), encoding="utf-8", newline="\n")
    total : int = sum(len(f['events']) for c in categories for f in c['families'])
    print(f"Wrote {total} event codes to {OUT.relative_to(ROOT)}/")


if __name__ == "__main__":
    Main()
